// Split wrapper: modules are grouped by responsibility for readability.
#include "mix_sig_modules/common_theme_cache_workspace.inl"
#include "mix_sig_modules/rng_star_models_and_host_math.inl"
#include "mix_sig_modules/rng_star_device_and_build_kernels.inl"
#include "mix_sig_modules/plan_core_planet_layout_kernels.inl"
#include "mix_sig_modules/plan_core_finalize_and_compact_kernels.inl"
#include "mix_sig_modules/seedbuild_and_flatsoa_defs.inl"
#include "mix_sig_modules/flatsoa_build_and_theme_hash_kernel.inl"
#include "mix_sig_modules/direct_pose_pipeline_direct_from_pose.inl"
#include "mix_sig_modules/direct_pose_pipeline_flat_eval.inl"
#include "mix_sig_modules/mix_driver_entry.inl"
